export default {
  "0480b142": [() => import(/* webpackChunkName: "0480b142" */ "@site/docs/faq.md"), "@site/docs/faq.md", require.resolveWeak("@site/docs/faq.md")],
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "401a4ed1": [() => import(/* webpackChunkName: "401a4ed1" */ "@site/docs/use-cases.md"), "@site/docs/use-cases.md", require.resolveWeak("@site/docs/use-cases.md")],
  "5281b7a2": [() => import(/* webpackChunkName: "5281b7a2" */ "@site/docs/architecture.md"), "@site/docs/architecture.md", require.resolveWeak("@site/docs/architecture.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6d103974": [() => import(/* webpackChunkName: "6d103974" */ "@site/docs/why-this-project.md"), "@site/docs/why-this-project.md", require.resolveWeak("@site/docs/why-this-project.md")],
  "72e14192": [() => import(/* webpackChunkName: "72e14192" */ "@site/docs/quick-start.md"), "@site/docs/quick-start.md", require.resolveWeak("@site/docs/quick-start.md")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aaeb7df5": [() => import(/* webpackChunkName: "aaeb7df5" */ "/home/user/snowflake-employee-experience-chatbot/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/home/user/snowflake-employee-experience-chatbot/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/home/user/snowflake-employee-experience-chatbot/website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],
  "e6ccb422": [() => import(/* webpackChunkName: "e6ccb422" */ "@site/docs/comparison.md"), "@site/docs/comparison.md", require.resolveWeak("@site/docs/comparison.md")],
  "f535dff1": [() => import(/* webpackChunkName: "f535dff1" */ "@site/docs/security-governance.md"), "@site/docs/security-governance.md", require.resolveWeak("@site/docs/security-governance.md")],};
